import {StyleSheet, Dimensions} from 'react-native';

const {height: viewHeight} = Dimensions.get('screen');

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFF',
    position: 'relative',
    flexDirection: 'column-reverse',
  },
  header: {
    position: 'relative',
    backgroundColor: '#6B26BB',
    height: viewHeight * 0.38,
    borderBottomRightRadius: 55,
    borderBottomLeftRadius: 55,
  },
  search: {
    width: 50,
    height: 50,
    position: 'absolute',
    backgroundColor: 'rgba(255, 255, 255, 0.25)',
    borderRadius: 10,
    top: 30,
    left: 14,
    zIndex: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  svgContainer: {
    flex: 1,
  },
  mainText: {
    position: 'absolute',
    top: viewHeight * 0.4 * 0.35,
    left: 14 + 25,
    fontSize: 28,
    fontWeight: 'bold',
    color: '#FFF',
    letterSpacing: 0.02,
  },
  secondaryText: {
    position: 'absolute',
    top: viewHeight * 0.4 * 0.35 + 40,
    left: 14 + 25,
    fontSize: 18,
    fontWeight: '300',
    width: 250,
    color: '#FFF',
    letterSpacing: 0.02,
  },
  form: {
    flex: 1,
  },
  inputGroup: {
    flexDirection: 'column',
    marginHorizontal: 40,
    marginBottom: 11,
  },
  textInput: {
    fontSize: 18,
    fontWeight: '600',
    color: '#5C5C5C',
  },
  inputDescription: {
    height: 110,
    textAlignVertical: 'top',
  },
  inputFile: {
    elevation: 0,
    borderColor: '#E9EEF2',
    borderWidth: 2,
    borderStyle: 'dashed',
    alignItems: 'flex-start',
    justifyContent: 'center',
  },
  previewName: {
    fontSize: 14,
    color: '#5C5C5C',
  },
  input: {
    marginTop: 3,
    elevation: 2,
    height: 55,
    fontSize: 16,
    alignItems: 'center',
    color: '#5C5C5C',
    padding: 10,
    backgroundColor: '#FFF',
    borderRadius: 10,
  },
  fileBoxItemLabels: {
    marginTop: 10,
    marginHorizontal: 40,
    flexDirection: 'row',
  },
  label: {
    fontSize: 14,
    marginLeft: 5,
    backgroundColor: '#E7395E',
    color: '#FFF',
    paddingHorizontal: 30,
    paddingVertical: 7,
    borderRadius: 15,
    textTransform: 'uppercase',
  },
  saveButton: {
    marginHorizontal: 40,
    height: 50,
    borderRadius: 10,
    backgroundColor: '#6B26BB',
    marginTop: 40,
    elevation: 4,
    alignItems: 'center',
    justifyContent: 'center',
  },
  saveButtonText: {
    fontSize: 20,
    textTransform: 'uppercase',
    color: '#FFF',
    fontWeight: 'bold',
    letterSpacing: 0.2,
  },
});
